services:
  mysql:
    image: mysql:8.0
    container_name: codeseries-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: codeseries
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/MySQL_dump.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  postgresql:
    image: postgres:16
    container_name: codeseries-postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: codeseries
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/PostgreSQLmigration.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo:7.0
    container_name: codeseries-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: codeseries
    ports:
      - "27017:27017"
    volumes:
      - ./src/main/resources/MongoDBmigration_full.js:/docker-entrypoint-initdb.d/init.js
