version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: codeseries-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: codeseries
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/MySQL_dump.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
