spring:
  profiles:
    active: mongodb  # Options: mysql, postgresql, mongodb

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  application:
    name: CodeSeries

jwt:
  expirationMs: 600000
